<?xml version="1.0" encoding="UTF-8"?>
<ActionCollection version="2" name="Scripts">
    <Actions category="Scripts">
        <text>Temporary Eraser</text>

        <Action name="temporaryEraserHold">
        <icon></icon>
        <text>Temporary Eraser(Hold)</text>
        <whatsThis></whatsThis>
        <toolTip></toolTip>
        <iconText></iconText>
        <activationFlags>10000</activationFlags>
        <activationConditions>0</activationConditions>
        <shortcut>ctrl+alt+shift+E</shortcut>
        <isCheckable>true</isCheckable>
        <statusTip></statusTip>
        </Action>
        
</ActionCollection>